### ISSUE TITLE
MemoryError while running ./install.sh

### ISSUE THREAD

**Issue by Nosen92** [pimoroni/pirate-audio#14]
Using a Raspberry Pi Zero W 512MB.

Installation crashes while installing Pirate Audio plugins:

```
Installing Pirate Audio plugins...
Collecting Mopidy-PiDi
  Using cached https://files.pythonhosted.org/packages/7b/8a/a06fdd1d34e7b2899493493525d9dc3b11415318bb6bb950def8a9be0339/Mopidy-PiDi-0.2.0.tar.gz
Collecting pidi-display-pil
  Using cached https://files.pythonhosted.org/packages/ac/a7/a92af23d84077fa714a100ddb86cff548ce25b6a379f449b86538600b772/pidi-display-pil-0.1.0.tar.gz
Collecting pidi-display-st7789
  Using cached https://files.pythonhosted.org/packages/c7/c9/7f959d62aef6634416642332081838fcaa097a3360130f67d628088b7987/pidi-display-st7789-0.1.0.tar.gz
Collecting mopidy-raspberry-gpio
  Using cached https://files.pythonhosted.org/packages/02/88/d8f7d071e0d1b3c2fa661781c143fa999e6949cdf2a187d5b7a1e4b63b59/Mopidy-Raspberry-GPIO-0.0.2.tar.gz
Requirement already up-to-date: Mopidy>=2.2 in /usr/local/lib/python2.7/dist-packages (from Mopidy-PiDi)
Requirement already up-to-date: Pykka>=2.0 in /usr/local/lib/python2.7/dist-packages (from Mopidy-PiDi)
Collecting musicbrainzngs>=0.6 (from Mopidy-PiDi)
  Using cached https://files.pythonhosted.org/packages/63/cc/67ad422295750e2b9ee57c27370dc85d5b85af2454afe7077df6b93d5938/musicbrainzngs-0.6.tar.gz
Collecting netifaces (from Mopidy-PiDi)
  Using cached https://files.pythonhosted.org/packages/0d/18/fd6e9c71a35b67a73160ec80a49da63d1eed2d2055054cc2995714949132/netifaces-0.10.9.tar.gz
Collecting setuptools (from Mopidy-PiDi)
  Using cached https://files.pythonhosted.org/packages/f9/d3/955738b20d3832dfa3cd3d9b07e29a8162edb480bf988332f5e6e48ca444/setuptools-44.0.0-py2.py3-none-any.whl
Collecting Pillow (from pidi-display-pil)
  Downloading https://files.pythonhosted.org/packages/b3/d0/a20d8440b71adfbf133452d4f6e0fe80de2df7c2578c9b498fb812083383/Pillow-6.2.2.tar.gz (37.8MB)
    99% |############################### | 37.8MB 1.5MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 380, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError

Resetting /etc/mopidy/mopidy.conf to package defaults.
```

**Comment by Nosen92** [comment]
Issue resolved after reinstalling raspbian to latest version.
